// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RubiksCube.Infrastructure.Persistence;

#nullable disable

namespace RubiksCube.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RubiksDbContext))]
    [Migration("20260928092446_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("RubiksCube.Domain.Sessions.CubeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cube")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("Facelets");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CubeSessions", (string)null);
                });

            modelBuilder.Entity("RubiksCube.Domain.Sessions.CubeSession", b =>
                {
                    b.OwnsMany("RubiksCube.Domain.Sessions.RotationLogEntry", "Log", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Sequence")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Face")
                                .HasMaxLength(8)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("OccurredAtUtc")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Rotation")
                                .HasMaxLength(16)
                                .HasColumnType("TEXT");

                            b1.HasKey("SessionId", "Sequence");

                            b1.ToTable("RotationLog", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
